# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application plus pull and merge

on:
  pull_request:
    branches: [ "main" ]
    types: 
      - opened
      - synchronize
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: sync main
      run: |
        git fetch origin
        git checkout update-branch
        git merge origin/main --allow-unrelated-histories --no-edit
        git push origin update-branch


    - name: create pull
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automated PR to main"
        body: "This PR was created automatically by GitHub Actions."
        base: main
        branch: update-branch
        delete-branch: false

    - name: merge pull
      if: steps.cpr.outputs.pull-request-url != ''
      run: |
        gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --merge --admin --delete-branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
