# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    types: 
      - opened
      - synchronize
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    #Flask dosent require a build.

     #Tests work but will fail due to no database present.   
    #- name: Test with unittest
      #run: testapp.py

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
          title: "Automated PR to main"
          body: "This PR was created automatically."
          base: main
          branch: update-branch
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge pull request
      if: steps.cpr.outputs.pull-request-url != ''
      run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --merge --admin --delete-branch
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
