# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    types: 
      - opened
      - synchronize
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Make dummy change (for demo)
      run: |
        echo "Updated at $(date)" >> update-log.txt

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create new branch and push changes
      run: |
        git checkout -b update-branch
        git add .
        git commit -m "Automated update commit" || echo "No changes to commit"
        git push origin update-branch || echo "Branch already exists"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automated PR to main"
        body: "This PR was created automatically by GitHub Actions."
        base: main
        branch: update-branch
        delete-branch: false

    - name: Merge Pull Request
      if: steps.cpr.outputs.pull-request-url != ''
      run: |
        gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --merge --admin --delete-branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
